version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./lambda_sns_function/init.sql:/docker-entrypoint-initdb.d/init.sql


  lambda_sns_function:
    build:
      context: ""
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: db
      DB_PORT: 3306

