== Python lambda with AWS SNS sample event

**Requirements**

For building and running:

* Docker latest version
* Python >= 3.7

**Building package**

Clean build:

The build command builds or rebuild images in the ```docker-compose.yml``` file
    ```
    docker-compose build
    ```


The command that aggregates the output of each container
    ```
    docker-compose up
    ```


**Application Local Run**

As the script is running as the main program inside the service lambda_sns_function it's possible to ensure the adding of resourses in the mysql table.

. Retrieve the container with ```docker-compose ps``` command (lists containers for a Compose project, with current status and exposed ports.)
. Connect to the mysql database with ```docker exec -it <container_name> mysql -u root -p```
. Insert the password
. Use the database with ```use db;```
. Show available table ```show tables;```
. Select a row from the table ```select * from resources;``` to make sure that the snapshot was correctly saved



Stops containers and removes containers, networks, volumes, and images created by up
    ```
    docker-compose down
    ```


**Info**

Developers:

* Togzhan Seksen